### ISSUE TITLE
Update Docs repo regarding how to use templates

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-documentation-planning#13] opened 2013-08-27 00:35 UTC
In the Docs repo README, Introduce the templates and provide general usage directions

**Comment by mojavelinux** [comment] 2021-02-17 08:18
Duplicate of https://github.com/asciidoctor/asciidoctor/issues/3948.

**Closed by mojavelinux** 2021-02-17 08:18 UTC
Labels: content-edit, infrastructure
