### ISSUE TITLE
Create Contributor Manual Template

### ISSUE THREAD

**Issue by graphitefriction** [asciidoctor/asciidoctor-documentation-planning#6] opened 2013-08-20 00:37 UTC
Produce template covering contribution guidelines and conventions for all aspects of the Asciidoctor project including:
- Website
- Docs
- Core Code
- Integration Code
- Extensions Code

**Comment by jaredmorgs** [comment] 2015-12-23 03:33
I think even describing how docs contributors should name their PRs (Issue-123) and suggesting how they use `git commit -amend` to update one commit with their PR content would be hugely helpful. 

These may be reflex actions to most experience git users, but folks who are perhaps using Asciidoctor as their first Open Source GitHub foray may find this type of guidance invaluable.

**Comment by mojavelinux** [comment] 2015-12-23 04:55
I agree (and I have no doubt Sarah does too) that being explicit is good. Like giving driving directions, choose big landmarks instead of subtle clues that are hard to detect.

**Comment by mojavelinux** [comment] 2021-02-17 08:26
This is now a duplicate of https://github.com/asciidoctor/asciidoctor-community-docs/issues/2.

**Closed by mojavelinux** 2021-02-17 08:26 UTC
Labels: content-new, infrastructure
